CREATE TABLE participantes(
ID int AUTO_INCREMENT PRIMARY KEY,
CPF char(14) NOT NULL UNIQUE,
NOME varchar(100) NOT NULL,
EMAIL varchar(100) NOT NULL,
TELEFONE varchar(11) NOT NULL,
LOGRADOURO varchar(100),
COMPLEMENTO varchar(100),
CIDADE varchar(50),
ESTADO char(2),
PAIS varchar(10),
TITULACAO ENUM ('TECNICO', 'TECNOLOGO', 'LICENCIADO', 'BACHAREL', 'MBA', 'MESTRE', 'DOUTOR', 'POS_DOC'),
INSTITUICAO varchar(100),
LOGIN varchar(100),
SENHA varchar(50)
);